library/catalog/urls.py
# from django.contrib import admin
from django.urls import path, include 
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('books', views.BookListView.as_view(), name='books'),
	path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
	path('authors', views.AuthorListView.as_view(), name='authors'),
	path('author/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
	path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
	path('book/<uuid:pk>/renew/', views.renew_book_librarian, name='renew-book-librarian'),
	path('author/create/', views.AuthorCreate.as_view(), name='author_create'),
    path('author/<int:pk>/update/', views.AuthorUpdate.as_view(), name='author_update'),
    path('author/<int:pk>/delete/', views.AuthorDelete.as_view(), name='author_delete'),
    path('book/create/', views.BookCreate.as_view(), name='book_create'),
    path('book/<int:pk>/update/', views.BookUpdate.as_view(), name='book_update'),
    path('book/<int:pk>/delete/', views.BookDelete.as_view(), name='book_delete'),
]
 

library/library/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='catalog/', permanent=True)),
    path('catalog/', include('catalog.urls')),
    path('accounts/', include('django.contrib.auth.urls'))

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

library/catalog/models.py
from django.db import models
from django.urls import reverse 
import uuid
from django.contrib.auth.models import User
from datetime import date 
# Create your models here.

class Genre(models.Model):

	name=models.CharField(max_length=200, help_text="Enter a book genre")

	def __str__(self):
		return self.name 
class Language(models.Model):
	name=models.CharField(max_length=200, help_text='Enter natural language of the book')	

	def __str__(self):
		return self.name 	

class Book(models.Model):

	title=models.CharField(max_length=200)
	summary=models.TextField(max_length=1000, help_text="Enter the book description")
	author=models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
	isbn=models.CharField('ISBN', max_length=13, help_text= '13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>"')
	genre=models.ManyToManyField(Genre, help_text="Choose a genre for the book")
	languange=models.ManyToManyField(Language, help_text="Choose a languagefor the book")
	cover=models.ImageField(upload_to='book', blank=True, null=True)
	
	def display_genre(self):
		return ','.join(genre.name for genre in self.genre.all()[:3])
	display_genre.short_description='Genre'	

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('book-detail', args=[str(self.id)])

class BookInstance(models.Model):
	id=models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="Unique Id for the book across the librays")
	book=models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
	imprint=models.CharField(max_length=200)
	due_back=models.DateField(null=True, blank=True)
	LOAN_STATUS=(
    		('m', 'Maintenance'),
    		('o', 'On Loan'),
    		('a', 'Available'),
    		('r', 'Reserved'),
    	)
	status=models.CharField(
    	max_length=1, choices=LOAN_STATUS, default='m', blank=True, help_text="Books availability")
	borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
	class Meta:
    	 ordering=['due_back']
	def __str__(self):
		return f'{self.id}, ({self.book.title})'

	@property
	def is_overdue(self):
		if self.due_back and date.today()>self.due_back:
			return True

		return False

	class Meta:
      
		permissions = (("can_mark_returned", "Set book as returned"),)   	
			 



class Author(models.Model):
	first_name=models.CharField(max_length=200)
	last_name=models.CharField(max_length=100)
	date_of_birth = models.DateField(null=True, blank=True)
	date_of_death=models.DateField('Died',null=True, blank=True)


	class Meta:
		ordering=['last_name', 'first_name']



	def get_absolute_url(self):
		return reverse('author-detail', args=[str(self.id)])

	def __str__(self):
		return f'{self.first_name}, {self.last_name}'		

		

library/catalog/forms.py
from django import forms
import datetime
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

class RenewBookForm(forms.Form):
	
	renewal_date =forms.DateField(help_text="Enter a dtae between now and 4 weeks (default 3)")

	def clean_renewal_data(self):

		data=self.cleaned_data['renewal_date']

		if data < datetime.date.today():
			raise ValidationError(_('Invalid date - renewal is past'))

		if data >datetime.date.today() + datetime.timedelta(weeks=4):
			raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))

		return data		

library/catalog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Book, BookInstance, Author, Genre
from django.views import generic
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
from catalog.forms import RenewBookForm
# Create your views here.
from django.contrib.auth.decorators import permission_required


@permission_required('catalog.can_mark_returned')
def renew_book_librarian(request, pk):
    	book_instance = get_object_or_404(BookInstance, pk=pk)

    	if request.method == 'POST':

    		form = RenewBookForm(request.POST)

    		if form.is_invalid():

    			book_instance.due_back = form.cleaned_data['renewal_date']
    			book_instance.save()

    			return HttpResponseRedirect(reverse('/'))

    		else:
    		

    			proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)	
    			form = RenewBookForm(initial={'renewal_date': proposed_renewal_date})

    		context={
	    		'form':form,
	    		'book_instance':book_instance,
    		}	

    		return render(request, 'catalog/book_renew_librarian.html', context)


def index(request):

	num_books=Book.objects.all().count()
	num_instances=BookInstance.objects.all().count()
	num_instances_available=BookInstance.objects.filter(status__exact='a').count()

	num_authors=Author.objects.count()
	num_genre=Genre.objects.all().count()

	num_visits =request.session.get('num_visits', 0)
	request.session['num_visits']=num_visits+1


	context={
	'num_books':num_books,
	'num_instances':num_instances,
	'num_instances_available':num_instances_available,
	'num_authors':num_authors,
	'num_genre':num_genre,
	'num_visits':num_visits
	}
	return render(request, 'index.html', context=context)

from django.contrib.auth.mixins import LoginRequiredMixin

class BookListView(LoginRequiredMixin, generic.ListView):
	
	model=Book	

	context_object_name='book_list'
	queryset=Book.objects.filter(title__icontains="") [:50]
	template_name='books/book_list.html'
	paginate_by =13

class BookDetailView(generic.DetailView):
	
		model=Book	

		def book_detail_view(request, primary_key):
			book=get_object_or_404(Book, pk=primary_key)
			return render(request, 'catalog/book_detail.html', context={'book':book})
class AuthorListView(generic.ListView):
	model=Author	
	paginate_by =2			

class AuthorDetailView(generic.DetailView):
	 model = Author 

	 # def author_detail_view(request, primary_key):
	 # 	author=get_object_or_404(Author, pk=primary_key)
	 # 	return render(request, 'catalog/author_detail.html', context={'author':author})


from django.contrib.auth.mixins import LoginRequiredMixin

class LoanedBooksByUserListView(LoginRequiredMixin,generic.ListView):
    """Generic class-based view listing books on loan to current user."""
    model = BookInstance
    template_name ='catalog/bookinstance_list_borrowed_user.html'
    paginate_by = 10
    
    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import PermissionRequiredMixin
from catalog.models import Author

class AuthorCreate(PermissionRequiredMixin, CreateView):
	model=Author
	fields = '__all__'
	initial ={'date of death': '05/01/2020'}

	permission_required='can_mark_returned'

class AuthorUpdate(PermissionRequiredMixin, UpdateView):
	model=Author
	fields=['first_name', 'last_name', 'date_of_birth', 'date_of_death']
	permission_required='can_mark_returned'

class AuthorDelete(PermissionRequiredMixin, DeleteView):
	model=Author
	success_url=reverse_lazy('authors')		
	permission_required='can_mark_returned'

class BookCreate(PermissionRequiredMixin, CreateView):
	model=Book
	fields = '__all__'
	initial ={'date of death': '05/01/2020'}
	permission_required='can_mark_returned'


class BookUpdate(PermissionRequiredMixin, UpdateView):
	model=Book
	fields='__all__'
	permission_required='can_mark_returned'

class BookDelete(PermissionRequiredMixin, DeleteView):
	model=Book
	success_url=reverse_lazy('books')	

	permission_required='can_mark_returned'
		

library/catalog/templates/catalog/author_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Author</h1>

<p>Are you sure you want to delete the author: {{ author }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

library/catalog/templates/catalog/author_detail.html
{% extends 'base_generic.html'%}
{% block content %}
<p><strong>First Name:</strong><a href=""></a>{{author.first_name}}</p>
<p><strong>Last Name:</strong>{{author.last_name}}</p>
<p><strong>Date of Birth:</strong>{{author.date_of_birth}}</p>
<p><strong>Date of Death:</strong>{{author.date_of_death}}</p>


{% endblock %}}

library/catalog/templates/catalog/author_form.html
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

library/catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}
{% block title %}<title>Authors</title>{% endblock %}
{% block content %}
  <h1>Author List</h1>

  {% if author_list %}
 
  
    {% for author in author_list %}
      
      	<div class="row">
  		<div class="col-lg-10 offset-lg-2">

  <div class="card d-lg-flex p-2 shadow-lg p-5 m-10" style="margin-top: 70px; margin-left: 70px;">
  <div class="card-header">
   <h2 class="text-center text-warning">{{ author.first_name }} {{author.last_name }}</h2>
  </div>
  <div class="card-body">
    <h5 class="card-title text-center text-danger">Born: {{ author.date_of_birth}} Died: {{author.date_of_death }}</h5>
    <p class="card-text text-center" >
    	<button class="btn btn-dark " type="submit">
    		<a href="{% url 'books' %}">View details</a> 
    
    	</button>
   

      
  </p>
    
  </div>
</div>

 

  </div>
  	</div>
 		
      
      
    {% endfor %}
  
  {% else %}
    <p>There are no books in the library.</p>
  {% endif %}       
{% endblock %}

library/catalog/templates/catalog/book_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Book</h1>

<p>Are you sure you want to delete the book: {{ book }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

library/catalog/templates/catalog/book_detail.html
{% extends 'base_generic.html'%}
{% block content %}
<div class="row">
  		<div class="col-lg-10 offset-lg-2">

  <div class="card d-lg-flex p-2 shadow-lg p-5 m-10" style="margin-top: 70px; margin-left: 70px;">
  <div class="card-header">
   <h2 class="text-center"> <h1 class="text-danger">Tittle: {{book.title}}</h1>
  </div>
  <div class="card-body">
   
	<p><strong>Author:</strong><a href="{% url 'author-detail' book.author.pk %}">{{book.author}}</a></p>
	<p><strong>Summary:</strong>{{book.summary}}</p>
	<p><strong>ISBN:</strong>{{book.isbn}}</p>
	<p><strong>Language:</strong>{{book.language}}</p>
	<p><strong>Genre:</strong>{{book.genre.all|join:","}}</p>
	<div style="margin-left:20px;margin-top:20px">
	    <h4>Copies</h4>

    {% for copy in book.bookinstance_set.all %}
      <hr>
      <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
        {{ copy.get_status_display }}
      </p>
      {% if copy.status != 'a' %}
        <p><strong>Due to be returned:</strong> {{ copy.due_back }}</p>
      {% endif %}
      <p><strong>Imprint:</strong> {{ copy.imprint }}</p>
      <p class="text-muted"><strong>Id:</strong> {{ copy.id }}</p>
       <p><strong>Borrower:</strong> {{ copy.borrower }}</p>
    {% endfor %}
  </div>
      
  </p>
    <a href="{{ book.get_absolute_url }}" class="btn btn-dark">view details</a>
  </div>
</div>

 

  </div>
  	</div>

{% endblock %}}

library/catalog/templates/catalog/book_form.html
{% extends "base_generic.html" %}

{% block content %}


	<h2 class="text-center text-danger">Add a Book</h2>
				
	<form class="book" action="" method="post">
			    {% csrf_token %}
			    <table border="1" style="margin-left:300px;">
			    {{ form.as_table }}
			    </table>
			    <div class="col text-center">
			    	<button type="submit" class="btn btn-primary btn-lg" value="Submit">Submit</button>
			    </div>
			    
			  </form>
				
  
{% endblock %}

library/catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}
{% block title %}<title>Books</title>{% endblock %}
{% block content %}
  <h1>Books In Our Library</h1>
    {% if book_list %}
  
    {% for book in book_list %}
      

  
  
  
  	<div class="row">
  		<div class="col-lg-10 offset-lg-2">

  <div class="card d-lg-flex p-2 shadow-lg p-5 m-10" style="margin-top: 70px; margin-left: 70px;">
  <div class="card-header">
   <h2 class="text-center text-warning">{{ book.author }}</h2>
  </div>
  <div class="card-body">
    <h5 class="card-title text-center text-danger">{{ book.title }}</h5>
    <p class="card-text text-center" >

        

      
  </p>
    <a href="{{ book.get_absolute_url }}" class="btn btn-dark">view details</a>
  </div>
</div>

 

  </div>
  	</div>
 		
       {% endfor %}
 	
     
  {% else %}
    <p>There are no books in the library.</p>
  {% endif %}
  
{% endblock %}

library/catalog/templates/catalog/book_renew_librarian.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Renew: {{ book_instance.book.title }}</h1>
  
  <p>Borrower: {{ book_instance.borrower }}</p>
  <p{% if book_instance.is_overdue %} class="text-danger"{% endif %}>Due date: {{ book_instance.due_back }}</p>
    
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

library/catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "base_generic.html" %}
{% block title %}<title>Borrowed Books</title>{% endblock %}
{% block content %}
    <h1>Borrowed books</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %} 
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }})        
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}       
{% endblock %}